export const ADD_USER_COIN_START = "ADD_USER_COIN_START";
export const ADD_USER_COIN_SUCCESS = "ADD_USER_COIN_SUCCESS";
export const ADD_USER_COIN_FAIL = "ADD_USER_COIN_FAIL";
export const ADD_USER_COIN = "ADD_USER_COIN";

export const REMOVE_USER_COIN_START = "REMOVE_USER_COIN_START";
export const REMOVE_USER_COIN_SUCCESS = "REMOVE_USER_COIN_SUCCESS";
export const REMOVE_USER_COIN_FAIL = "REMOVE_USER_COIN_FAIL";
export const REMOVE_USER_COIN = "REMOVE_USER_COIN";

export const UPDATE_USER_COIN_START = "UPDATE_USER_COIN_START";
export const UPDATE_USER_COIN_SUCCESS = "UPDATE_USER_COIN_SUCCESS";
export const UPDATE_USER_COIN_FAIL = "UPDATE_USER_COIN_FAIL";
export const UPDATE_USER_COIN = "UPDATE_USER_COIN";

export const FETCH_USER_COINS_START = "FETCH_USER_COINS_START";
export const FETCH_USER_COINS_SUCCESS = "FETCH_USER_COINS_SUCCESS";
export const FETCH_USER_COINS_FAIL = "FETCH_USER_COINS_FAIL";
export const FETCH_USER_COINS = "FETCH_USER_COINS";
